use rk;
show tables;
select * from myemp;
select * from myemp limit 100;
select * from myemp limit 15;
select emp_id,salary from myemp;
select emp_id,hire_date,salary from myemp limit 15;
select * from myemp;
select first_name,last_name,salary from myemp limit 10;
select first_name,last_name,salary, salary/0.15 from myemp limit 10;
select first_name, last_name ,salary,salary/0.15 as Bonus from myemp limit 10;
select concat(first_name," ", last_name), salary, salary/0.15 as Bonus from myemp limit 10;
select * from myemp;
select  Hire_date, emp_id, salary, round(salary /0.15,0) as Bonus from myemp;
select * from myemp;
select dep_id from myemp;
select distinct dep_id from myemp;
select distinct dep_id from myemp order by dep_id;
select dep_id from myemp order by dep_id desc ;
select distinct dep_id from myemp order by dep_id desc;
select distinct dep_id from myemp order by dep_id  desc;
select * from myemp;
select distinct salary from myemp;
select concat(first_name, " " , last_name)as Nammes from myemp where salary > 10000;
select * from person;
select distinct fname from person;
select distinct lname from person;
select distinct fname, lname from person;
select * from myemp;
select  concat(first_name," " ,last_name)as Namess ,salary from myemp where salary >=2500;
select * from myemp where dep_id =60;
select * from myemp where salary < 2500;
select * from myemp where dep_id !=60;
select * from myemp where dep_id = 90;
select * from myemp where dep_id <>60;
select *from myemp where salary = 5000 & 25000;
select * from myemp where hire_date = 2020-12-31 and 2021-12-31;
select * from myemp where first_name = "j%";
select  first_name from myemp where last_name ="j%";
select  last_name from myemp where first_name like "%g";
select first_name from myemp where first_name like "j%";
select first_name from myemp where first_name like "%a";
select first_name from myemp where first_name like "a____";
select first_name from myemp where first_name like "____a";
select first_name from myemp where first_name like "%c%";